# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class MgmtsystemAction(models.Model):
    _inherit = "mgmtsystem.action"

    # ondelete="set null", unlike every other link in this system: an action is
    # the record of work done and must outlive its source. OCA already refuses
    # to delete an inspection that is not in draft
    # (qc_inspection._unlink_except_autogenerated_and_non_draft), so the only
    # inspection that can disappear is one nobody confirmed, and an action that
    # survives it with an empty link loses nothing. "restrict" would instead
    # make a draft inspection undeletable because someone raised an action.
    qms_inspection_id = fields.Many2one(
        comodel_name="qc.inspection",
        string="Inspection",
        ondelete="set null",
        index=True,
        help="The inspection this action was raised from.",
    )

    def action_view_qms_inspection(self):
        """Open the source inspection.

        The button is hidden when the field is empty rather than offering to
        create an inspection: an inspection is raised by a quality-control
        trigger or by hand in Quality Control, never sensibly from an action,
        so there is nothing to prefill in this direction.
        """
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": self.env._("Inspection"),
            "res_model": "qc.inspection",
            "res_id": self.qms_inspection_id.id,
            "view_mode": "form",
        }
