# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class MgmtsystemAction(models.Model):
    _inherit = "mgmtsystem.action"

    # ondelete="set null", unlike every other link in this system: an action is
    # the record of work done and must outlive its source. OCA already refuses
    # to delete an inspection that is not in draft
    # (qc_inspection._unlink_except_autogenerated_and_non_draft), so the only
    # inspection that can disappear is one nobody confirmed, and an action that
    # survives it with an empty link loses nothing. "restrict" would instead
    # make a draft inspection undeletable because someone raised an action.
    qms_inspection_id = fields.Many2one(
        comodel_name="qc.inspection",
        string="Inspection",
        ondelete="set null",
        index=True,
        help="The inspection this action was raised from.",
    )

    # No smart button on this side: the field is itself a link to the
    # inspection, so a button would be a second way to do the same thing. The
    # aggregate direction is the one that earns a button, and it lives on
    # qc.inspection, where a count summarises records no field shows.
